language: python
sudo: required

python:
  - "2.7"

services:
  - docker

before_install:
  - docker pull pyhrf/pyhrf

install:
  - pip install coveralls

script:
  - docker run --name pyhrf -d pyhrf/pyhrf sleep 300
  - docker exec pyhrf /bin/sh -c "nosetests --with-doctest --with-coverage --cover-package=pyhrf -v -s pyhrf"
  - docker exec pyhrf cat .coverage > .coverage

after_success:
  - coveralls
