sudo: required

language: python

services:
  - docker

before_install:
  - docker pull pyhrf/pyhrf

script:
  - docker run --rm pyhrf/pyhrf /bin/sh -c "nosetests --with-doctest --with-coverage --cover-package=pyhrf -v -s pyhrf"

after_success:
    - coveralls
