sudo: required

services:
  - docker

before_install:
  - git clone https://github.com/pyhrf/docker-pyhrf.git
  - docker build --build-arg PYHRF_BRANCH=$TRAVIS_BRANCH -t pyhrf/pyhrf docker-pyhrf

script:
  - docker run --rm -v ${PWD}:/output:rw -e LOCAL_USER_ID=`id -u $USER` pyhrf/pyhrf bash -c "nosetests --with-doctest --with-coverage --cover-package=pyhrf -v -s pyhrf && cp .coverage /output"

after_success:
  - docker run --rm -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -v ${PWD}:/output:rw -e LOCAL_USER_ID=`id -u $USER` pyhrf/pyhrf bash -c "cd /output; coveralls"
  - if [ -n "$TRAVIS_TAG" ]; then
      docker tag pyhrf/pyhrf pyhrf/pyhrf:$TRAVIS_TAG;
      docker login -u $DOCKER_USER -p $DOCKER_PASS
      docker push pyhrf/pyhrf:$TRAVIS_TAG;
    fi

env:
  global:
  - secure: D44j7Z0fd8m4CmmwvywCtXqT7yqamA7uCIyN5CjD+Ovu1MwCSjkhYBpET5cDMznDhl+JsAWUJBaicCbNSaDKlCWY4FWwZB9Ss9xo+09vqA6iVIc1sBGJzd3knTM+WaJ5sjnQDqAiQfizEgPiDekztrFlXkmdvE5CNeiqg1Ph6F8=
  - secure: F9LDFuZWNnNSMYNcfQFJLhs2okHyFYeRMvz5xZAwTSKBReKXO7XMmZNyVtRndraR7+i9uABRrafWeFSLw0sC22kXz7x0qMXX1lg+J0J45m52xCtSaxJhJ+qfEUn+e+nqOREABxzzK4DkTZ1Y2jILllHzD6czmqeHEk9J6IJkzKk=
