sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - docker pull pyhrf/pyhrf
  - docker run --rm pyhrf/pyhrf /bin/sh -c "nosetests --with-doctest --with-coverage --cover-package=pyhrf -v -s pyhrf"

install: "pip install coveralls"

script: coveralls
