sudo: required

services:
  - docker

before_install:
  - git clone https://github.com/pyhrf/docker-pyhrf.git
  - docker build --build-arg PYHRF_BRANCH=$TRAVIS_BRANCH --build-arg DEPLOY=true -t pyhrf/pyhrf docker-pyhrf

script:
  - docker run --rm -v ${PWD}:/output:rw -e LOCAL_USER_ID=`id -u $USER` pyhrf/pyhrf \
      bash -c "nosetests --with-doctest --with-coverage --cover-package=pyhrf -v -s pyhrf && cp .coverage /output"

after_success:
  - docker run --rm -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -v ${PWD}:/output:rw -e LOCAL_USER_ID=`id -u $USER` pyhrf/pyhrf bash -c "cd /output; coveralls"
  - docker run --rm -v ${PWD}:/output:rw -e LOCAL_USER_ID=`id -u $USER` pyhrf/pyhrf bash -c "cp -r /pyhrf/dist /output"
  - if [ -n "$TRAVIS_TAG" ]; then
      docker tag pyhrf/pyhrf pyhrf/pyhrf:$TRAVIS_TAG;
      docker login -u $DOCKER_USER -p $DOCKER_PASS;
      docker push pyhrf/pyhrf:$TRAVIS_TAG;
    fi

deploy:
  provider: pypi
  user: pyhrf
  password:
    secure: ObKoWykbyp2VrUiIQWgFg842+6a40k+n4SP6mXDfJbEiN5qXYKHrJp12d7RXQ7kw+rUqiCsXqPv+mZya3oLiOtOXurnq8XpqqiT9iFMmfmGsY+YICJf0B1SNnctlZ9wZOPThn8jroKYNn5FsjDFn8VYLvIIdeXUEjlBuL6qMw8Y=
  skip_cleanup: true
  on:
    tags: true

env:
  global:
  - secure: bYWR3RZ1qWDfba6ayukpvfGSkoObyLTUzr0yeIXSR6a24iRoNEiwL1g/OJAtaZNMgVMSNrawvZpr3T+6Bu/3WILHrN9iK2p5q/31GwtXQJJJMsy5KH43+doP+P0siHdXbcEPt7VWpOFxS540AG/+7lzS78Qtj3XKWV6B8+pqkWs=
  - secure: gOua7OkapIyvsKekFoTGRKnzcGNXfENz2eTKZ0npuJB2KfNN4OOrncaJXgW3NFbj8qugZMqmXsvGnDTbW6Ihc+iICXaHlJTKsXcLQX8bRnBBmBNoLHvypHg0xqHUpZRc1Id5A07k18PxbVx86lt3W2WTpCrsSxM9ccGgS2wvtU0=
