language: python
sudo: required

python:
  - "2.7"

services:
  - docker

before_install:
  - docker pull pyhrf/pyhrf
  - mkdir coverage_output

script:
  - docker run --rm -v ${PWD}/coverage_output:/output:rw -e LOCAL_USER_ID=`id -u $USER` pyhrf/pyhrf \
    bash -c "nosetests --with-doctest --with-coverage --cover-package=pyhrf -v -s pyhrf; cp .coverage /output"

after_success:
  - mv coverage_output/.coverage .coverage
  - sed -i "s/\"\/pyhrf/\"$(echo ${TRAVIS_BUILD_DIR} | sed 's/\//\\\//g')/g" .coverage
  - coveralls
